### ISSUE TITLE
DCCP solver only iterates once?

### ISSUE THREAD

**Issue by vanhecke1** [cvxgrp/qcqp#3]
Hi,

I tried to use DCCP method for my non-convex qcqp problem, but it looks like the DCCP method terminates after 1 iteration. I would like to learn the reasoning behind this procedure. 

Thanks a lot!

**Comment by jaehyunp** [comment]
DCCP may have found a local optimum in a single iteration. May I see your script or a minimal example so that I can accurately determine what is going on? Thanks.

**Comment by vanhecke1** [comment]
Hi,

Looks like I somehow installed an older DCCP version, sorry about that. Thanks for quick response!
