### ISSUE TITLE
    from Utility import * ImportError: No module named Utility

### ISSUE THREAD

**Issue by VijayaLakshmiPottimurthy** [cvxgrp/qcqp#4]
I am trying to execute the python proxy.py. But I got the error     from Utility import *
ImportError: No module named Utility

I have already installed Utility folder from pip ( pip install utility) 

what I have to install to resolve this issue ?? I am using python 2.7 and Windows 10

**Comment by jaehyunp** [comment]
Is this error from QCQP, or something else? QCQP does not import anything called Utility.

**Comment by jvvvv** [comment]
hello，I also encountered the same problem. Have you solved it?
