### ISSUE TITLE
Trying to import qcqp in anaconda envrionment

### ISSUE THREAD

**Issue by sangyoonstat** [cvxgrp/qcqp#5]
Hello,

I've tried using qcqp in anaconda environment. It has been installed by using pip command in the anaconda directory but whenever I am trying to import qcqp it gives me the following error:

>>> import qcqp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sangyoon/anaconda3/lib/python3.6/site-packages/qcqp/__init__.py", line 25, in <module>
    from qcqp import QCQP
ImportError: cannot import name 'QCQP'

Is this because I cannot use qcqp in the anaconda even after successful installation ? Thank you, in advance.

**Comment by mudream4869** [comment]
I meet same error under mac anaconda terminal : 

```
>>> import qcqp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mudream/anaconda/lib/python3.5/site-packages/qcqp/__init__.py", line 25, in <module>
    from qcqp import QCQP
ImportError: cannot import name 'QCQP'
```

Is the error only occur in anaconda environment ?  😢

**Comment by mudream4869** [comment]
change `__init__.py` to 

```python
from qcqp.qcqp import QCQP
from qcqp.settings import RANDOM, SPECTRAL, SDR
from qcqp.settings import COORD_DESCENT, ADMM, DCCP, IPOPT
```

and it works ...

**Comment by jaehyunp** [comment]
thank you both, I'll update the code right away.

**Comment by DonghanHe** [comment]
Actually I tired the quick fix above, and now I have a different error, which is 
`----> 1 import qcqp

/Users/donghanhe/anaconda3/lib/python3.5/site-packages/qcqp/__init__.py in <module>()
     23 """
     24 
---> 25 from qcqp.qcqp import QCQP
     26 from qcqp.settings import RANDOM, SPECTRAL, SDR
     27 from qcqp.settings import COORD_DESCENT, ADMM, DCCP, IPOPT

/Users/donghanhe/anaconda3/lib/python3.5/site-packages/qcqp/qcqp.py in <module>()
     30 from numpy import linalg as LA
     31 import scipy.sparse.linalg as SLA
---> 32 from utilities import *
     33 import logging
     34 import settings as s

ImportError: No module named 'utilities'`

This has actually appeared in another [issue](https://github.com/cvxgrp/qcqp/issues/1)

**Comment by jaehyunp** [comment]
sorry for the inconveniences. until I can test it on a mac machine, do you mind changing the line 32 of `qcqp.py` to the following and trying again?
`from qcqp.utilities import *`

**Comment by jaehyunp** [comment]
fixed. this was due to the import behavior difference in python2 and python3. please update your qcqp installation with `pip install qcqp --upgrade`, and it should work now.
