### ISSUE TITLE
Import error in python

### ISSUE THREAD

**Issue by Harshvardhan1** [cvxgrp/qcqp#6]
An error arises in the line "from qcqp import * " saying:-
NameError: name 'QCQP' is not defined

I used pip to install cvxpy and qcqp and I'm working in python 2.7.

Please tell me how to fix this.
Thanks in advance

**Comment by jaehyunp** [comment]
sorry for the inconveniences. I've meant to fix the pip version import error for some time. I'll try to fix it sometime this week. meanwhile, please directly install from this repository.

**Comment by Harshvardhan1** [comment]
Can you elaborate on the manual installation procedure

Thanks

**Comment by jaehyunp** [comment]
fixed. this was due to the import behavior difference in python2 and python3. please update your qcqp installation with `pip install qcqp --upgrade`, and it should work now.
